"""initial migration with constraints

Revision ID: ddc6c5ba709c
Revises: b8f7b869b6da
Create Date: 2025-07-16 14:20:08.858199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc6c5ba709c'
down_revision: Union[str, None] = 'b8f7b869b6da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'permissions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'role_permissions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permissions_id'], ['id'])
    op.create_foreign_key(None, 'roles', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    # ### end Alembic commands ###
